export class SourceBookList {

  get books(): Array<any> {
    const list = [
      { abbrev: 'CP20', name: 'Cyberpunk 2020 2nd ed.'                , affLink: 'https://collabs.shop/4bbktq', pdfLink: '' },
      { abbrev: 'BB'  , name: "R Bartmoss' Brainware Blowout"         , affLink: 'https://collabs.shop/lcnvfz', pdfLink: '' },
      { abbrev: 'BH'  , name: "Blackhand's Street Weapons"            , affLink: 'https://collabs.shop/pkv6vp', pdfLink: '' },
      { abbrev: 'CB1' , name: 'Corpbook 1'                            , affLink: 'https://collabs.shop/l3yqm3', pdfLink: '' },
      { abbrev: 'CB2' , name: 'Corpbook 2'                            , affLink: 'https://collabs.shop/l3yqm3', pdfLink: '' },
      { abbrev: 'CB3' , name: 'Corpbook 3'                            , affLink: 'https://collabs.shop/l3yqm3', pdfLink: '' },
      { abbrev: 'CHR1', name: 'Chromebook 1'                          , affLink: 'https://collabs.shop/qkl6nh', pdfLink: '' },
      { abbrev: 'CHR2', name: 'Chromebook 2'                          , affLink: 'https://collabs.shop/qkl6nh', pdfLink: '' },
      { abbrev: 'CHR3', name: 'Chromebook 3'                          , affLink: 'https://collabs.shop/bqdbrx', pdfLink: '' },
      { abbrev: 'CHR4', name: 'Chromebook 4'                          , affLink: 'https://collabs.shop/bqdbrx', pdfLink: '' },
      { abbrev: 'DS'  , name: 'Deep Space'                            , affLink: 'https://collabs.shop/e9gnsn', pdfLink: '' },
      { abbrev: 'ER'  , name: 'Edgerunner Inc.'                       , affLink: 'https://collabs.shop/vylogi', pdfLink: '' },
      { abbrev: 'ES+' , name: 'Eurosource Plus'                       , affLink: 'https://collabs.shop/h57ja0', pdfLink: '' },
      { abbrev: 'ES'  , name: 'Eurosource'                            , affLink: 'https://collabs.shop/h57ja0', pdfLink: '' },
      { abbrev: 'ET'  , name: 'Eurotour'                              , affLink: 'https://collabs.shop/u0ij77', pdfLink: '' },
      { abbrev: 'FH'  , name: 'Forlorn Hope'                          , affLink: 'https://collabs.shop/o6oo5l', pdfLink: '' },
      { abbrev: 'HOB' , name: 'Home of the Brave'                     , affLink: 'https://collabs.shop/4pebco', pdfLink: '' },
      { abbrev: 'HW'  , name: 'Hardwired'                             , affLink: ''                           , pdfLink: '' },
      { abbrev: 'LOF' , name: 'Land of the Free'                      , affLink: ''                           , pdfLink: '' },
      { abbrev: 'LD'  , name: 'Live & Direct'                         , affLink: 'https://collabs.shop/yfiap5', pdfLink: '' },
      { abbrev: 'LU'  , name: 'Listen Up, You Primitive Screwheads!!!', affLink: 'https://collabs.shop/vopvml', pdfLink: '' },
      { abbrev: 'MM'  , name: 'Maximum Metal'                         , affLink: 'https://collabs.shop/1osp7o', pdfLink: '' },
      { abbrev: 'NC'  , name: 'Night City'                            , affLink: 'https://collabs.shop/vvmyya', pdfLink: '' },
      { abbrev: 'NEO' , name: 'Neo Tribes'                            , affLink: 'https://collabs.shop/v58ffr', pdfLink: '' },
      { abbrev: 'NET' , name: "Rache Bartmoss' Guide to the Net"      , affLink: ''                           , pdfLink: '' },
      { abbrev: 'PAC' , name: 'Pacific Rim Sourcebook'                , affLink: 'https://collabs.shop/foptk2', pdfLink: '' },
      { abbrev: 'PS'  , name: 'Protect & Serve'                       , affLink: 'https://collabs.shop/vlofm5', pdfLink: '' },
      { abbrev: 'RB'  , name: 'Rockerboy'                             , affLink: 'https://collabs.shop/07ozaf', pdfLink: '' },
      { abbrev: 'SF'  , name: 'Firestorm: Stormfront'                 , affLink: 'https://collabs.shop/5zjqyp', pdfLink: '' },
      { abbrev: 'SOF' , name: 'Solo of Fortune'                       , affLink: ''                           , pdfLink: '' },
      { abbrev: 'SOF2', name: 'Solo of Fortune 2'                     , affLink: 'https://collabs.shop/duxivx', pdfLink: '' },
      { abbrev: 'SW'  , name: 'Firestorm: Shockwave'                  , affLink: 'https://collabs.shop/bphbpw', pdfLink: '' },
      { abbrev: 'WGF' , name: 'When Gravity Fails'                    , affLink: 'https://collabs.shop/gfulxu', pdfLink: '' },
      { abbrev: 'UK'  , name: 'Rough Guide to the U.K.'               , affLink: 'https://collabs.shop/amoo0c', pdfLink: '' },
      { abbrev: 'WS'  , name: 'Wildside'                              , affLink: 'https://collabs.shop/srae0x', pdfLink: '' },
      { abbrev: 'I1.1', name: 'Interface 1.1'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'I1.2', name: 'Interface 1.2'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'I1.3', name: 'Interface 1.3'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'I1.4', name: 'Interface 1.4'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'I2.1', name: 'Interface 2.1'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'I2.2', name: 'Interface 2.2'                         , affLink: ''                           , pdfLink: '' },
      { abbrev: 'EOS' , name: 'Edge of the Sword'                     , affLink: 'https://collabs.shop/c4cfpq', pdfLink: '' },
      { abbrev: 'FUZ' , name: 'Fuzion Rule Book'                      , affLink: 'https://collabs.shop/ek0ysa', pdfLink: '' },

      { abbrev: 'CPR'    , name: 'Cyberpunk Red'                        , affLink: 'https://collabs.shop/1bsvws', pdfLink: 'https://collabs.shop/b31gbd' },
      { abbrev: 'CPRBC'  , name: 'Black Chrome'                         , affLink: 'https://collabs.shop/hkbxom', pdfLink: 'https://collabs.shop/6xdxwb' },
      { abbrev: 'CPRTRSS', name: 'Tales of the Red: Street Stories'     , affLink: 'https://collabs.shop/lexmun', pdfLink: 'https://collabs.shop/6qtcza' },
      { abbrev: 'CPRTRHR', name: 'Tales of the Red: Hope Reborn'        , affLink: 'https://collabs.shop/eb1pxe', pdfLink: 'https://collabs.shop/qrwjwa' },
      { abbrev: 'CPRGMS' , name: 'GameMaster Screens'                   , affLink: 'https://collabs.shop/htibwr', pdfLink: '' },
      { abbrev: 'CPRJSK' , name: 'Cyberpunk Red: Jumpstart Kit'         , affLink: 'https://collabs.shop/jspi6s', pdfLink: 'https://collabs.shop/jtynhy' },
      { abbrev: 'CPRDP'  , name: 'Data Pack'                            , affLink: 'https://collabs.shop/pzfyln', pdfLink: 'https://collabs.shop/ukygq0' },
      { abbrev: 'CPRDGD' , name: 'Danger Gal Dossier'                   , affLink: 'https://collabs.shop/guefvj', pdfLink: 'https://collabs.shop/edy8b4' },
      { abbrev: 'CPRERMK', name: 'Cyberpunk Red: Edgerunner Mission Kit', affLink: 'https://collabs.shop/iwx1r9', pdfLink: 'https://collabs.shop/nsmtoy' },
      { abbrev: 'CPRI1'  , name: 'Interface 1'                          , affLink: 'https://collabs.shop/2dultq', pdfLink: '' },

    ];
    return list;
  }
}
